<#import "websocketmaster.ftlh" as m/>
<@m.master>
	<div class="site-wrapper">
		<div class="site-wrapper-inner">
    		<div class="cover-container">
    			<div class="inner cover">
    				 <ul class="breadcrumb">
                      <li><a href="#">Vote</a></li>
                      <li><a class="active" href="#">Graveyard</a></li>
                    </ul>
   			 	</div>
			</div>
   		</div>
	</div>
</@m.master>